services:
  db:
    container_name: mysql
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: first_chat
      MYSQL_USER: pop
      MYSQL_PASSWORD: chickenattack
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
    driver: local
